server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiweile/springcloud.git
          searchPaths: springcloud-config-repo/authservice
          username: xiweile
          password: xwl8416655
          clone-on-start: true
        encrypt:
          enabled: false
    bus:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test
management:
  endpoints:
    web:
      exposure:
        include: ["bus-refresh","bus-env"]