server:
  port: 8002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: springcloud-product #修改别名
    prefer-ip-address: true

spring:
  application:
    name: springcloud-product

ribbon:
  client:
    name: springcloud-auth

springcloud-auth:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8001/user
