server:
  port: 8002
#  servlet:
#   context-path: /product

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: springcloud-product #修改别名
    prefer-ip-address: true

spring:
  application:
    name: springcloud-product
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?useSSL=false
    username: root
    password: xiweile
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
mybatis-plus:
  mapper-locations: classpath:com/weiller/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #使用日志
ribbon:
  client:
    name: springcloud-auth

springcloud-auth:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
auth-server: http://localhost:8001/auth
security:
  oauth2:
   client:
        client-id: product
        client-secret: 123456
        access-token-uri: ${auth-server}/oauth/token
        user-authorization-uri: ${auth-server}/oauth/authorize
#        scope: read,write
#        auto-approve-scopes: '.*'
   resource:
        user-info-uri: ${auth-server}/me
        token-info-uri: ${auth-server}/oauth/check_token
#        jwt:
#           key-uri: ${auth-server}/oauth/token_key
#           key-value: weiller
logging:
  level:
    root: info