server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: springcloud-cusumer-8080

ribbon:
  client:
    name: SPRINGCLOUD-PRIVIDER-HELLO

SPRINGCLOUD-PRIVIDER-HELLO:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule