server:
  port: 9000
spring:
  application:
    name: springcloud-gateway
zuul:
  routes:
    auth:
      path: /auth/**
      url: springcloud-auth
    product:
      path: /product/**
      url: springcloud-product

