server:
  port: 9000
spring:
  application:
    name: springcloud-gateway
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8 #最大连接数
        max-wait: -1  #最大阻塞等待时间(负数表示没限制)
        max-idle: 8   #最大空闲数
        min-idle: 0   #最小空闲数
    timeout: 10000
zuul:
  prefix: /
  routes:
    auth:
      path: /auth/**
      url: springcloud-auth
    product:
      path: /product/**
      url: springcloud-product
  sensitive-headers: ''
  ignored-patterns:
  add-host-header: true
  retryable: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: springcloud-gateway	#修改别名
    prefer-ip-address: true		    #显示IP地址

# 过滤器参数配置
filter.path:
  ignores: /login,/logout
  login: /auth/login
  logout: /auth/logout

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 50000

session.redis.duetime: 1 #单位分钟