server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: springcloud-auth	#修改别名
    prefer-ip-address: true		    #显示IP地址
spring:
  application:
    name: springcloud-auth

info:
  author: weiller
  service-url: http://localhost:$server.port$/