server:
  port: 8003

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    #instance-id: privider8001	#修改别名
    prefer-ip-address: true		#显示IP地址
spring:
  application:
    name: springcloud-privider-hello

info:
  author: weiller
  service-url: http://localhost:$server.port$/